### ISSUE TITLE
Add some interop unit tests for endpoints

### ISSUE THREAD

**Issue by jmeas** [jmeas/moolah#125]
- GET nonexistent, then create it, then GET it again
- GET existing, then delete it, then GET it again
- GET existing, then patch it, then GET it again
- GET all, create one, then GET all again
- GET all, delete one, then GET all again

**Comment by vitaly-t** [comment]
Maybe not strictly related...

```js
function getInsertQuery(values) {
  // Ensure that each key exists – even if it's null. pg-promise
  // will error otherwise. For more, reference:
  // https://github.com/vitaly-t/pg-promise#named-parameters
  values = _.map(values, v => {
    return _.defaults(v, {
      date: null,
      description: null,
      value: null
    });
  });
  var formattedValues = new Inserts('${date}, ${description}, ${value}', values);
  return ['INSERT INTO transaction(date, description, value) VALUES $1', formattedValues];
}
```

But regarding:

>Ensure that each key exists – even if it's null. pg-promise will error otherwise

It will only throw when the property doesn't exist at all. It can be either `null` or `undefined`, both are transformed into `null`, as per [Named Parameters](https://github.com/vitaly-t/pg-promise#named-parameters):

>It is important to know that while property values null and undefined are both formatted as null, an error is thrown when the property doesn't exist at all.

**Comment by jmeas** [comment]
Yup yup - that's why I'm using _.defaults there to ensure all of the keys at least exist

**Comment by vitaly-t** [comment]
On this subject, [version 3.2.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.2.0) has just changed this ;) It is now more flexible ;)

**Comment by jmeas** [comment]
Nice! This is a welcome addition. Thanks for the update, @vitaly-t .

**Comment by jmeas** [comment]
On the subject of these interop tests...I may do them, or I may not. I might turn the existing integration tests into unit tests, which would speed them up. But to do so would prob require mocking out pg-promise, which may give me false positives if the API changes down the road, and I don't catch it.

**Comment by vitaly-t** [comment]
Got it ;)

**Comment by jmeas** [comment]
Decided against these interop tests. Not sure that the value add is worth it
