### ISSUE TITLE
partial formatting

### ISSUE THREAD

**Issue by vitaly-t** [jmeas/moolah#159]
From here: https://github.com/jmeas/finance-app/blob/a670e2411f563c4905772b6036ece51b2c960409/test/integration/api/transactions/index.js#L15

I don't know if this is of any help to you, but on your comment there:

>pg-promise will error otherwise. 

just wanted to point out - this is the default behavior indeed. But if you are relying on `pgp.as.format` method directly, it has third parameter `options` where setting `partial` will disable bombing out on missing parameters. See [its API](http://vitaly-t.github.io/pg-promise/formatting.html#.format).

Just in case you ever need this kind of functionality.

For example, it is used by type `QueryFile` when it provides static pre-formatting for queries ;)

**Comment by jmeas** [comment]
Amazing. Definitely going to take advantage of that. Thanks for the suggestion, @vitaly-t !

**Comment by jmeas** [comment]
Gonna leave the code as-is for now, but this is good to know for the future.
