### ISSUE TITLE
Refactor away use of findDOMNode

### ISSUE THREAD

**Issue by jmeas** [jmeas/moolah#361]
[ref](https://github.com/yannickcr/eslint-plugin-react/issues/678)

I [only use it in 1 place](https://github.com/jmeas/moolah/blob/b08bec052c1cdbc93238c2e9ff742180fc1ebe42/client-src/categories/components/modify-category-modal/index.js).

**Comment by gaearon** [comment]
>ref

Pun intended? 😄

**Comment by jmeas** [comment]
ahahaha – it wasn't, actually! 😆
